[package]
name = "rustray"
version = "0.1.0"
edition = "2024"

[dependencies]
bmp = "0.5.0"
glam = "0.30.2"
rand = "0.9.0"
sdl3 = { version = "0.14.23", features = ["build-from-source-static"] }

[profile.dev]
opt-level = 2
